= Demonstration

Des exemples de base de données pour la démonstration du logiciel.
À des fins de démonstration, une seule base de données (`uhf`) est utilisée. Elle contient le schéma `UHF` (fonctions utilitaires),
le schéma de la base de données source (non historicisée) et le schéma de la base de données historicisée.
Chaque exemple est stocké dans un schéma différent.

== Pré-requis

Logiciels : 

* Serveur PostgreSQL 
* Java 14+ 
* [optionel] Un client de BD (pgAdmin or DataGrip).

Pour PostgreSQL, nous devons créer un ensemble de fonctions utilitaires.
Avec un utilisateur PostgreSQL disposant des privilèges CREATE DATABASE.

. Rendre le script exécutable depuis la racine du projet: `chmod u+x ./lib/uhf-base/UHF-base_build.sh`.

[NOTE]
====
Si vous utilisez Windows, vous devez utiliser Git Bash et exécuter: `chmod u+x ./lib/uhf-base/UHF-base_build.sh`
====

[start=2]
. Exécuter depuis la racine du projet: `./lib/uhf-base/UHF-base_build.sh -h`, pour voir les options disponibles.

[NOTE]
====
Si vous utilisez Windows, ajouter `bash` avant la commande :

. `bash ./lib/uhf-base/UHF-base_build.sh -h`, pour voir les options disponibles.
====

[start=3]
. Exécuter depuis la racine du projet: `./lib/uhf-base/UHF-base_build.sh -b <database>`, en remplaçant `<database>` par le nom de votre base de données. +
Exemple: `./lib/uhf-base/UHF-base_build.sh -b postgres`

[NOTE]
====
Si vous utilisez Windows, ajouter `bash` avant la commande :

. `bash ./lib/uhf-base/UHF-base_build.sh -u <user> -b <database>` en remplaçant `<database>` par le nom de votre base de données et
`<user>` par le nom d'utilisateur PostgreSQL.
====

Le schéma `UHF` contenant les fonctions utilitaires sera créé dans la base de données `uhf`.

== Supplier-Part

. Constuire le schéma initial :
.. Dans un client BD executer le fichier : `demo/Supplier-Part/src/table_cresql`. **OU**
.. Dans un terminal : `psql -d uhf -f demo/Supplier-Part/src/table_cre.sql`
. Modifier le fichier de configuration au besoin : +
`demo/Supplier-Part/configuration/config.yaml`

[NOTE]
====
Le paramètre `rdbmsPath` dans le fichier de configuration doit être adapté selon le chemin d'installation de PostgreSQL sur votre machine. Par exemple :

* macOS (Postgres.app) : `/Applications/Postgres.app/Contents/Versions/<version>/bin/psql`
* Linux : `/usr/bin/psql`
* Windows : `C:\Program Files\PostgreSQL\<version>\bin\psql.exe`
====

. Exécuter UHF-SQL dans un terminal : +
   `java -jar uhf-sql-0.2.0-SNAPSHOT.jar demo/Supplier-Part/configuration/config.yaml`

== MIMIC-IV Hosp 

. Constuire le schéma initial :
.. `demo/mimiciv_hosp/src/table_cre.sql` and
.. `demo/mimiciv_hosp/src/constraint.sql`.
. Modifier le fichier de caonfiguration au besoin  : +
`demo/mimiciv_hosp/configuration/config.yaml`
. Exécuter UHF-SQL dans un terminal : +
`java -jar uhf-sql-0.2.0-SNAPSHOT.jar demo/mimiciv_hosp/configuration/config.yaml`



