= Demonstration

Database examples for the software demonstration.
For the demonstration purpose, one database (uhf) is used. It contains the `UHF` schema (utility functions),
the source (non-historicized) database schema, and the historicized database schema.
Each example will be stored in a different schema.

== Prerequisites

Softwares : 

* PostgreSQL database
* Java 14+ 
* [optional] DB client (pgAdmin or DataGrip).

For PostgreSQL we have a set of utility functions to create.
Using a PostgreSQL user with CREATE DATABASE privileges.

. Make the script executable from the project root: `chmod u+x ./lib/uhf-base/UHF-base_build.sh`.

[NOTE]
====
If you use Windows, you should use Git Bash and run: `chmod u+x ./lib/uhf-base/UHF-base_build.sh`.
====

[start=2]
. Execute from the project root: `./lib/uhf-base/UHF-base_build.sh -h`, to see the available options.

[NOTE]
====
If you use Windows, you should add `bash` before the command:

. `bash ./lib/uhf-base/UHF-base_build.sh -h` to see the available options.
====

[start=3]
. Execute from the project root: `./lib/uhf-base/UHF-base_build.sh -b <database>`, replacing `<database>` with the name of your database. +
Example: `./lib/uhf-base/UHF-base_build.sh -b postgres`

[NOTE]
====
If you use Windows, you should add `bash` before the command:

. `bash ./lib/uhf-base/UHF-base_build.sh -u <user> -b <database>` replacing `<database>` with the name of your database and
`<user>` with the PostgreSQL username.
====

The `UHF` schema containing the utility functions will be created in the `uhf` database.

== Supplier-Part

. Build the initial schema :
.. In a DB IDE execute `demo/Supplier-Part/src/table_cre.sql` **OR**
.. In a terminal: `psql -d uhf -f demo/Supplier-Part/src/table_cre.sql`
. Modify the configuration if needed: +
`demo/Supplier-Part/configuration/config.yaml`

[NOTE]
====
The `rdbmsPath` parameter in the configuration file must be adapted to your PostgreSQL installation path. For example:

* macOS (Postgres.app) : `/Applications/Postgres.app/Contents/Versions/<version>/bin/psql`
* Linux : `/usr/bin/psql`
* Windows : `C:\Program Files\PostgreSQL\<version>\bin\psql.exe`
====

. Execute UHF-SQL in a terminal: +
   `java -jar uhf-sql-0.2.0-SNAPSHOT.jar demo/Supplier-Part/configuration/config.yaml`

== MIMIC-IV Hosp 

. Build the initial schema :
.. `demo/mimiciv_hosp/src/table_cre.sql` and
.. `demo/mimiciv_hosp/src/constraint.sql`.
. Modify the configuration if needed: +
`demo/mimiciv_hosp/configuration/config.yaml`
. Execute UHF-SQL in a terminal: +
`java -jar uhf-sql-0.2.0-SNAPSHOT.jar demo/mimiciv_hosp/configuration/config.yaml`



