= Demonstration

Database examples for the software demonstration.

== Prerequisites

Softwares : 

* PostgreSQL database
* Java 14+ 
* [optional] DB client (pgAdmin or DataGrip).

For PostgreSQL we have a set of utility functions to create.
Using a PostgreSQL user with CREATE DATABASE privileges. 

. Execute `UHF-base_build.sh`

For the demonstration purpose, one database (uhf) is used.
Each example will be stored in a different schema.

[NOTE]
====
The `rdbmsPath` parameter in the configuration file must be adapted to your PostgreSQL installation path. For example:

* macOS (Postgres.app) : `/Applications/Postgres.app/Contents/Versions/17/bin/psql`
====

== Supplier-Part

. Build the initial schema :
.. In a DB IDE execute `demo/Supplier-Part/src/table_cre.sql` **OR**
.. In a terminal: `psql -d uhf -f demo/Supplier-Part/src/table_cre.sql`
. Modify the configuration if needed: +
`demo/Supplier-Part/configuration/config.yaml`
. Execute UHF-SQL in a terminal: +
   `java -jar uhf-sql-0.2.0-SNAPSHOT.jar demo/Supplier-Part/configuration/config.yaml`

== MIMIC-IV Hosp 

. Build the initial schema :
.. `demo/mimiciv_hosp/sql/table_cre.sql` and 
.. `demo/mimiciv_hosp/sql/constraint.sql`.
. Modify the configuration if needed: +
`demo/mimiciv_hosp/configuration/config.yaml`
. Execute UHF-SQL in a terminal: +
`java -jar uhf-sql-0.2.0-SNAPSHOT.jar demo/mimiciv_hosp/configuration/config.yaml`



